# A generic, single database configuration for Alembic.

[alembic]
# Path to migration scripts
script_location = alembic

# Template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for local time
timezone = UTC

# max length of characters which are used to render the --autogenerate title
# max_length = 40

[post_write_hooks]
# hooks defined here will run after a new migration script is generated.

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
